import pathlib
from datetime import date


def write_rd():
    doc = """
# COVID-autumn-forecast

HI, this readme is autogenerated when main.py is run.
latest update --> {}

The data used in the forecasts is available at [pcm-dpc covid repository](https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json)

## Risultati


#### Stati Europei

Italia vs UK vs Francia: morti

![april vs september](images/gdeaths.png)

Italia vs UK vs Francia: nuovi casi

![april vs september](images/ginfections.png)

Italia vs Francia: terapia intensiva

![april vs september](images/gintensive.png)



#### Previsioni

Previsione a 2 settimane nel futuro del numero di casi in **terapia intensiva**. (modello `Yapprossimata=Ae^(Bx)`)

![april vs september](images/predictionint.png)

Previsione a 2 settimane nel futuro del numero di nuovi casi. (modello `Yapprossimata=Ae^(Bx)`)

![april vs september](images/prediction.png)

#### Aprile vs Settembre

Persone in ospedale causa covid: aprile e settembre

![april vs september](images/aprilseptember.png)

Morti in **Veneto** causa covid: aprile e settembre

![april vs september](images/aprilseptemberve.png)

Morti in **Trentino** causa covid: aprile e settembre

![april vs september](images/aprilseptembertr.png)

Terapia Intensiva in **Veneto** causa covid: aprile e settembre

![april vs september](images/aprilseptemberveintensive.png)

Terapia Intensiva in **Lazio** causa covid: aprile e settembre

![april vs september](images/aprilseptemberveintensila.png)


#### Storici

Storico dei ricoverati in terapia intensiva

![casi intensivi](images/intensive.png)

Storico dei nuovi casi registrati

![new cases](images/infections.png)


    """.format(date.today())

    readme_path = pathlib.Path(__file__).parent.absolute() / ".." / "README.md"

    with open(readme_path, 'w') as fout:
        fout.write(doc)
