import pathlib
from datetime import date


def write_rd():
    doc = """
# COVID-autumn-forecast

HI, this readme is autogenerated when main.py is run.
latest update --> {}

The data used in the forecasts is available at [pcm-dpc covid repository](https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json)

## Risultati

Il primo grafico compara la crescita degli ospitalizzati ad aprile vs settembre

![april vs september](images/aprilseptember.png)

Il secondo grafico mostra il numero dei ricoverati in terapia intensiva nel tempo.
Ricordiamo che il primo lockdown avvenne il 18 aprile, quando il numero dei casi era intorno ai 2550

![april vs september](images/intensive.png)

L'ultimo grafico mostra una previsione a 2 settimane nel futuro. (modello `Yapprossimata=Ae^(Bx)`)

![april vs september](images/prediction.png)

    """.format(date.today())

    readme_path = pathlib.Path(__file__).parent.absolute() / ".." / "README.md"

    with open(readme_path, 'w') as fout:
        fout.write(doc)
